---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault_secrets.yml

patches:
  - path: helmrelease.yml
    target:
      kind: HelmRelease
      namespace: flux-services

  - target:
      kind: HelmRelease
      namespace: flux-services
    patch: |-
      - op: replace
        path: /metadata/name
        value: central-controller
